/*
 * OC - Oberon Compiler for 65C816
 * Copyright (C) 2024-2026 Jason Swain
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/* Definitions must be in alphabetical order */

DEF(ADC, "adc", F_INSTR)
DEF(ADD, "add", F_INSTR)
DEF(AND, "and", F_INSTR)
DEF(ASL, "asl", F_INSTR)
DEF(ASR, "asr", F_INSTR)
DEF(BAR, "bar", F_INSTR)
DEF(BAS, "bas", F_INSTR)
DEF(BBR, "bbr", F_INSTR)
DEF(BBS, "bbs", F_INSTR)
DEF(BCC, "bcc", F_INSTR)
DEF(BCS, "bcs", F_INSTR)
DEF(BEQ, "beq", F_INSTR)
DEF(BGE, "bge", F_INSTR)
DEF(BIT, "bit", F_INSTR)
DEF(BMI, "bmi", F_INSTR)
DEF(BNE, "bne", F_INSTR)
DEF(BPL, "bpl", F_INSTR)
DEF(BRA, "bra", F_INSTR)
DEF(BRK, "brk", F_INSTR)
DEF(BRL, "brl", F_INSTR)
DEF(BVC, "bvc", F_INSTR)
DEF(BVS, "bvs", F_INSTR)
DEF(CLC, "clc", F_INSTR)
DEF(CLD, "cld", F_INSTR)
DEF(CLI, "cli", F_INSTR)
DEF(CLV, "clv", F_INSTR)
DEF(CLW, "clw", F_INSTR)
DEF(CMP, "cmp", F_INSTR)
DEF(COP, "cop", F_INSTR)
DEF(CPX, "cpx", F_INSTR)
DEF(CPY, "cpy", F_INSTR)
DEF(DEC, "dec", F_INSTR)
DEF(DEX, "dex", F_INSTR)
DEF(DEY, "dey", F_INSTR)
DEF(EOR, "eor", F_INSTR)
DEF(EXC, "exc", F_INSTR)
DEF(INC, "inc", F_INSTR)
DEF(INI, "ini", F_INSTR)
DEF(INX, "inx", F_INSTR)
DEF(INY, "iny", F_INSTR)
DEF(JML, "jml", F_INSTR)
DEF(JMP, "jmp", F_INSTR)
DEF(JPI, "jpi", F_INSTR)
DEF(JSB, "jsb", F_INSTR)
DEF(JSL, "jsl", F_INSTR)
DEF(JSR, "jsr", F_INSTR)
DEF(LAB, "lab", F_INSTR)
DEF(LAI, "lai", F_INSTR)
DEF(LAN, "lan", F_INSTR)
DEF(LDA, "lda", F_INSTR)
DEF(LDX, "ldx", F_INSTR)
DEF(LDY, "ldy", F_INSTR)
DEF(LII, "lii", F_INSTR)
DEF(LSR, "lsr", F_INSTR)
DEF(MPA, "mpa", F_INSTR)
DEF(MPY, "mpy", F_INSTR)
DEF(MVN, "mvn", F_INSTR)
DEF(MVP, "mvp", F_INSTR)
DEF(NEG, "neg", F_INSTR)
DEF(NOP, "nop", F_INSTR)
DEF(NXT, "nxt", F_INSTR)
DEF(ORA, "ora", F_INSTR)
DEF(PEA, "pea", F_INSTR)
DEF(PEI, "pei", F_INSTR)
DEF(PER, "per", F_INSTR)
DEF(PHA, "pha", F_INSTR)
DEF(PHB, "phb", F_INSTR)
DEF(PHD, "phd", F_INSTR)
DEF(PHI, "phi", F_INSTR)
DEF(PHK, "phk", F_INSTR)
DEF(PHP, "php", F_INSTR)
DEF(PHW, "phw", F_INSTR)
DEF(PHX, "phx", F_INSTR)
DEF(PHY, "phy", F_INSTR)
DEF(PIA, "pia", F_INSTR)
DEF(PLA, "pla", F_INSTR)
DEF(PLB, "plb", F_INSTR)
DEF(PLD, "pld", F_INSTR)
DEF(PLI, "pli", F_INSTR)
DEF(PLP, "plp", F_INSTR)
DEF(PLW, "plw", F_INSTR)
DEF(PLX, "plx", F_INSTR)
DEF(PLY, "ply", F_INSTR)
DEF(PSH, "psh", F_INSTR)
DEF(PUL, "pul", F_INSTR)
DEF(RBA, "rba", F_INSTR)
DEF(REP, "rep", F_INSTR)
DEF(RMB, "rmb", F_INSTR)
DEF(RND, "rnd", F_INSTR)
DEF(ROL, "rol", F_INSTR)
DEF(ROR, "ror", F_INSTR)
DEF(RTI, "rti", F_INSTR)
DEF(RTL, "rtl", F_INSTR)
DEF(RTS, "rts", F_INSTR)
DEF(SBA, "sba", F_INSTR)
DEF(SBC, "sbc", F_INSTR)
DEF(SEC, "sec", F_INSTR)
DEF(SED, "sed", F_INSTR)
DEF(SEI, "sei", F_INSTR)
DEF(SEP, "sep", F_INSTR)
DEF(SMB, "smb", F_INSTR)
DEF(STA, "sta", F_INSTR)
DEF(STI, "sti", F_INSTR)
DEF(STP, "stp", F_INSTR)
DEF(STX, "stx", F_INSTR)
DEF(STY, "sty", F_INSTR)
DEF(STZ, "stz", F_INSTR)
DEF(SWA, "swa", F_INSTR)
DEF(TAD, "tad", F_INSTR)
DEF(TAS, "tas", F_INSTR)
DEF(TAW, "taw", F_INSTR)
DEF(TAX, "tax", F_INSTR)
DEF(TAY, "tay", F_INSTR)
DEF(TCD, "tcd", F_INSTR)
DEF(TCS, "tcs", F_INSTR)
DEF(TDA, "tda", F_INSTR)
DEF(TDC, "tdc", F_INSTR)
DEF(TIP, "tip", F_INSTR)
DEF(TRB, "trb", F_INSTR)
DEF(TSA, "tsa", F_INSTR)
DEF(TSB, "tsb", F_INSTR)
DEF(TSC, "tsc", F_INSTR)
DEF(TSX, "tsx", F_INSTR)
DEF(TWA, "twa", F_INSTR)
DEF(TXA, "txa", F_INSTR)
DEF(TXS, "txs", F_INSTR)
DEF(TXY, "txy", F_INSTR)
DEF(TYA, "tya", F_INSTR)
DEF(TYX, "tyx", F_INSTR)
DEF(WAI, "wai", F_INSTR)
DEF(WDM, "wdm", F_INSTR)
DEF(XBA, "xba", F_INSTR)
DEF(XCE, "xce", F_INSTR)
